### ISSUE TITLE
Vocab size not compatible with the configuration in the `dbmdz/bert-base-italian-*` models

### ISSUE THREAD

**Issue by simone-cangialosi** [dbmdz/berts#12]
The vocab size declared in the file `config.json` and the related dimensions of the model params (32102) are greater than the actual number of rows of the file `vocab.txt` (31102).

Is there a reason for that or the vocabulary file is not the correct one?

**Comment by stefan-it** [comment]
Hi @simone-cangialosi ,

you're right, there was an issue when training the model see: https://github.com/dbmdz/berts/issues/7. Fortunately, this mismatch seems not to harm to performance of the model.

However, we are in progress to train ELECTRA models for all languages, because we found the training stable and it requires less time for pre-processing. So expect some new ELECTRA models for Italian in near future :)

**Comment by simone-cangialosi** [comment]
Hi @stefan-it ,

thank you very much, everything is clear!

Let's wait for the ELECTRA models :)
