### ISSUE TITLE
How to train bert-base-italian-* models?

### ISSUE THREAD

**Issue by nikhilno1** [dbmdz/berts#4]
Thanks for sharing.
I want to train a different language model (Hindi).
How did you train your bert-base-italian-* models? Are those steps covered anywhere?

**Comment by stefan-it** [comment]
Hi @nikhilno1 ,

for training the Italian models we did the following steps:

* Collect corpora (we mainly used OPUS and OSCAR)
* Generate vocabulary (using SentencePiece, here's an [example command](https://github.com/allenai/scibert/blob/master/scripts/cheatsheet.txt#L6) in sciBERT repo and convert it to a BERT-compatible one
* Sentence splitting (we use NLTK, because it is much faster than spacy)
* Sharding (1GB text per shard)
* TFRecord generation for a sequence length of 512 (more information can be found in the official BERT [repo](https://github.com/google-research/bert#pre-training-with-bert) on that topic
* Train BERT model on TPU v3-8

I do plan to write a cheatsheet for an upcoming BERT model, where I use the awesome new Hugging Face [tokenizers library](https://github.com/huggingface/tokenizers) for creating the BERT vocab!

**Comment by stefan-it** [comment]
Hi @nikhilno1,

for the Turkish BERT model I created a cheatsheet for the training process:

https://github.com/stefan-it/turkish-bert/blob/master/CHEATSHEET.md

It also shows how to generate a BERT-compatible vocab.

I hope this helps + good luck with the Hindi model!

**Comment by nikhilno1** [comment]
Thanks for sharing. Will go through it.
